name: Psalm Security Scan

on: [push, pull_request]

defaults:
  run:
    shell: bash
    working-directory: app/plugin/doctrine/Doctrine/Symfony/Component/Yaml

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Psalm Security Scan
        uses: docker://ghcr.io/austenstone/psalm-security-scan
        env:
          INPUT_WORKING_DIR: app/plugin/doctrine/Doctrine/Symfony/Component/Yaml
          
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
